# Generated by Django 2.0.2 on 2018-03-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MegaSuploadAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filekey',
            name='key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='encrypted_priv_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_key',
            field=models.TextField(),
        ),
    ]
