# Generated by Django 2.0.2 on 2018-03-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MegaSuploadAPI', '0002_auto_20180304_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='file',
            name='permissions',
        ),
        migrations.AddField(
            model_name='permission',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MegaSuploadAPI.Directory'),
        ),
        migrations.AddField(
            model_name='permission',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MegaSuploadAPI.File'),
        ),
    ]
