# Generated by Django 2.0.2 on 2018-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MegaSuploadAPI', '0002_auto_20180319_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_data_allowed',
            field=models.BigIntegerField(default=32212254720),
        ),
    ]
